# Options that have something to do with generators / forges (or whatever you wanna call those)
generators:
  booster:
    # If the module is enabled
    enabled: true
    # How many resources should we drop in addition to the original generator drop
    # For example the default value 2, would drop 2 more iron ingots on 1 iron ingot drop from the generator
    drop-amount: 1
    # Delay on dropping multiplied amount from the original drop time (in seconds)
    # Leave it as it is if you don't know what this is and start tweaking multiply-by
    delay: 1
  limiter:
    # If the module is enabled
    enabled: true
    # Check radius (Amount would be in all directions XYZ)
    radius: 2
    # How many Items are allowed in the specified radius?
    limit: 20

  # Preventing some things from happening to make the gameplay better
  prevent:
    placing-block-on-chest: true
    placing-block-on-enderchest: true